dist: trusty
sudo: false
env:
  - EMACS_VERSION=25.1
  - EMACS_VERSION=25.2
  - EMACS_VERSION=25.3
  - EMACS_VERSION=26.1
  - EMACS_VERSION=git-snapshot
matrix:
  allow_failures:
    - env: EMACS_VERSION=git-snapshot
install:
  - git clone --depth 1 -b v0.14.0 https://github.com/rejeep/evm.git ~/.evm
  - export PATH="$HOME/.evm/bin:$PATH"
  - evm config path /tmp
  - evm install "emacs-$EMACS_VERSION-travis"
  - export PATH="/tmp/emacs-$EMACS_VERSION-travis/bin:$PATH"
  - emacs --version
script:
  - make
